languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: false
exclude_paths:
- "extension/content/newfeatures/*"
- "extension/defaults/*"
- "extension/content/pref/in-content/preferences.js"
- "extension/content/xbbcode.js"
- "extension/modules/prefs.js"
