engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
    - 2b4a128ee12814f53c4c67e5a14182d4
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- extension/content/newfeatures/*
- extension/defaults/*
- extension/content/pref/in-content/preferences.js
- extension/content/xbbcode.js
- extension/modules/prefs.js