git:
  depth: 25 # default: 50
language: node_js
node_js:
  - "node"
notifications:
  irc:
    channels: "irc.synirc.net#salr"
    on_success: change # [always|never|change] default: always
    on_failure: change # [always|never|change] default: always
before_script:
  - npm install -g gulp
script: npm test && gulp build
