git:
  depth: 1
language: node_js
node_js:
  - "node"
notifications:
  irc:
    channels: "irc.synirc.net#salr"
    on_success: always # [always|never|change] default: always
    on_failure: always # [always|never|change] default: always
before_script:
  - npm install -g grunt-cli
script: npm test && grunt build
